### ISSUE TITLE
Release Please not updating version

### ISSUE THREAD

**Issue by johnallen3d** [johnallen3d/conditions#24]
e.g. https://github.com/johnallen3d/conditions/pull/11

**Comment by johnallen3d** [comment]
Consider switching to [`release-plz`](https://marcoieni.github.io/release-plz/github-action.html).

```
name: Release-plz

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@main
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
