### ISSUE TITLE
Release Please Action Failing

### ISSUE THREAD

**Issue by johnallen3d** [johnallen3d/conditions#7]
Need to add the following to the action config:

```yaml
permissions:
  contents: write
  pull-requests: write
```

https://github.com/google-github-actions/release-please-action/issues/709#issuecomment-1407490618
