### ISSUE TITLE
Configure dependabot to review actions

### ISSUE THREAD

**Issue by johnallen3d** [johnallen3d/conditions#99]
Set up Dependabot to review GitHub actions in use for updates.

e.g.
```yaml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```
